name: 'Monitor CI Status'
description: 'Monitor and report CI status for AI sub-agents'

inputs:
  commit-sha:
    description: 'Commit SHA to monitor'
    required: true
  output-file:
    description: 'Output JSON file path'
    required: false
    default: 'ci_result.json'

outputs:
  status:
    description: 'CI status (success/failure)'
    value: ${{ steps.check.outputs.status }}

runs:
  using: composite
  steps:
    - name: Check CI status
      id: check
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        echo "Monitoring CI for commit ${{ inputs.commit-sha }}"

        # Wait for checks to complete
        sleep 10

        # Get check runs
        gh api repos/${{ github.repository }}/commits/${{ inputs.commit-sha }}/check-runs \
          --jq '.check_runs[] | {name: .name, status: .status, conclusion: .conclusion}' \
          > checks.json

        # Determine overall status
        if jq -e '.conclusion == "failure"' checks.json > /dev/null; then
          echo "status=failure" >> $GITHUB_OUTPUT
          STATUS="failure"
        else
          echo "status=success" >> $GITHUB_OUTPUT
          STATUS="success"
        fi

        # Create result JSON
        jq -n \
          --arg status "$STATUS" \
          --arg commit "${{ inputs.commit-sha }}" \
          --slurpfile checks checks.json \
          '{status: $status, commit: $commit, checks: $checks}' \
          > ${{ inputs.output-file }}

        cat ${{ inputs.output-file }}
