# C++ Pre-commit configuration
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=5000']
      - id: check-merge-conflict

  # C++ formatting and linting (optional tools)
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      # Only run clang-format if it's available
      - id: clang-format
        args: [--style=file]
        require_serial: false

      # Run clang-tidy with reasonable checks (less strict)
      - id: clang-tidy
        args: [
          -checks=readability-*,modernize-*,performance-*,bugprone-*,
          -warnings-as-errors=,
          --quiet,
          --use-color
        ]
        require_serial: false

      # Only run cppcheck if it's available (skip otherwise)
      - id: cppcheck
        args: [
          --enable=warning,style,performance,portability,
          --suppress=missingIncludeSystem,
          --inline-suppr,
          --error-exitcode=0
        ]
        require_serial: false
